# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build CSharpGuard

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: web-api
  AZURE_WEBAPP_PACKAGE_PATH: './publish'
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v4           
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Setup .NET    
      uses: actions/setup-dotnet@v4
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build CSharp.Guard/CSharp.Guard.csproj --configuration Debug --no-restore
      
    - name: Pack
      run: dotnet pack CSharp.Guard/CSharp.Guard.csproj -c Debug --no-restore --no-build
      
    - name: Push to NuGet
      ## oy2denvbjvpyobvxnmeauqdcwmcw7ave3oc3xddlwo5dsu
      ## ${{secrets.NUGET_API_KEY}}
      run: dotnet nuget push *.nupkg --skip-duplicate -s https://api.nuget.org/v3/index.json -k oy2denvbjvpyobvxnmeauqdcwmcw7ave3oc3xddlwo5dsu
